### ISSUE TITLE
suggestK

### ISSUE THREAD

**Issue by rzzli** [MacoskoLab/liger#83] opened 2019-07-11 17:44 UTC
Hi When I run suggestK, I ran into this error
"no applicable method for 'optimizeALS' applied to an object of class "c('double', 'numeric')""

please advise

**Comment by vkozareva** [comment] 2019-07-12 20:08
Could you give us a small reproducible example of your error case, and include your system info? 
Just from this error message, it seems like you may have tried to run the function on an integer instead of a liger object.

**Comment by vkozareva** [comment] 2019-07-25 16:26
Closing as we can't reproduce this error.

**Closed by vkozareva** 2019-07-25 16:26 UTC
