### ISSUE TITLE
error in suggestLambda

### ISSUE THREAD

**Issue by dhtc** [MacoskoLab/liger#124] opened 2019-10-23 00:47 UTC
When i run the function suggestLambda(sp.lobj,k=25,num.cores = 4), i met an error. It said as below:

[1] "This operation may take several minutes depending on number of values being tested"
[1] "Preprocessing for rep 1: optimizing initial factorization with smallest test lambda=0.25"
  |======================================================================| 100%
Converged in 33.36085 mins, 37 iterations.
Best results with seed 1.
[1] "Progress now represents completed factorizations (out of total number of lambda values)"
  |======================================================================| 100%
Error in {: task 13 failed - "missing value where TRUE/FALSE needed"
Traceback:

1. suggestLambda(sp.lobj, k = 25, num.cores = 4)
2. foreach(i = 1:length(lambda.test), .combine = "rbind", .options.snow = opts, 
 .     .packages = "liger") %dopar% {
 .     if (i != 1) {
 .         if (gen.new) {
 .             ob.test <- optimizeALS(object, k = k, lambda = lambda.test[i], 
 .                 thresh = thresh, max.iters = max.iters, rand.seed = (rand.seed + 
 .                   r - 1))
 .         }
 .         else {
 .             ob.test <- optimizeNewLambda(object, new.lambda = lambda.test[i], 
 .                 thresh = thresh, max.iters = max.iters, rand.seed = (rand.seed + 
 .                   r - 1))
 .         }
 .     }
 .     else {
 .         ob.test <- object
 .     }
 .     ob.test <- quantileAlignSNF(ob.test, knn_k = knn_k, k2 = k2, 
 .         resolution = resolution, ref_dataset = ref_dataset, id.number = i)
 .     calcAlignment(ob.test)
 . }
3. e$fun(obj, substitute(ex), parent.frame(), e$data)

So, i wander how to solve it? Thanks in advance.

**Comment by indajuan** [comment] 2019-11-05 11:28
Hi,

I am facing the same problem here. Have you got any solution to this?

Thank you,

**Comment by dhtc** [comment] 2019-11-08 14:29
> Hi,
> 
> I am facing the same problem here. Have you got any solution to this?
> 
> Thank you,

No.

**Comment by vkozareva** [comment] 2019-11-08 20:49
Hi! Unfortunately we haven't been able to reproduce this error on our machines -- could either of you give us the output of `sessionInfo()` or a small dataset that we can use to reproduce this?

**Comment by dsb66** [comment] 2019-11-27 19:40
I also have the same problem. I am running ( I have added the return.data and return.raw options to try and solve the problem):

ligerLambda.plot <- suggestLambda(liger, k = 35, num.cores = 8, 
                                  return.data = F, return.raw = F)

Execution stops with this message:

[1] "This operation may take several minutes depending on number of values being tested"
[1] "Preprocessing for rep 1: optimizing initial factorization with smallest test lambda=0.25"
  |========================================================================================| 100%
Converged in 59.05852 mins, 33 iterations.
Best results with seed 1.
[1] "Progress now represents completed factorizations (out of total number of lambda values)"
  |========================================================================================| 100%Error in { : task 3 failed - "missing value where TRUE/FALSE needed"
In addition: There were 15 warnings (use warnings() to see them)

Sample of warning messages (they are all the same except for the connection number):
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 17 (<-localhost:11695)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 16 (<-localhost:11695)
3: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 15 (<-localhost:11695)
4: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 14 (<-localhost:11695)

Here is my SessionInfo():

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/local/bin/miniconda3/lib/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] liger_0.4.2          patchwork_0.0.1.9000 Matrix_1.2-17        cowplot_1.0.0       
 [5] RColorBrewer_1.1-2   slingshot_1.2.0      Biobase_2.44.0       BiocGenerics_0.30.0 
 [9] princurve_2.1.4      future_1.14.0        ggthemes_4.2.0       forcats_0.4.0       
[13] stringr_1.4.0        dplyr_0.8.3          purrr_0.3.3          readr_1.3.1         
[17] tidyr_1.0.0          tibble_2.1.3         ggplot2_3.2.1        tidyverse_1.2.1     
[21] harmony_1.0          Rcpp_1.0.3           sctransform_0.2.0    SeuratWrappers_0.1.0
[25] Seurat_3.1.1        

loaded via a namespace (and not attached):
  [1] RANN.L1_2.5.2               R.methodsS3_1.7.1           pkgmaker_0.27              
  [4] bit64_0.9-7                 knitr_1.26                  irlba_2.3.3                
  [7] DelayedArray_0.10.0         R.utils_2.9.0               data.table_1.12.6          
 [10] RCurl_1.95-4.12             doParallel_1.0.15           generics_0.0.2             
 [13] snow_0.4-3                  metap_1.1                   RSQLite_2.1.2              
 [16] RANN_2.6.1                  bit_1.1-14                  phylobase_0.8.6            
 [19] webshot_0.5.1               xml2_1.2.2                  lubridate_1.7.4            
 [22] httpuv_1.5.2                SummarizedExperiment_1.14.1 assertthat_0.2.1           
 [25] viridis_0.5.1               xfun_0.11                   hms_0.5.2                  
 [28] promises_1.1.0              progress_1.2.2              caTools_1.17.1.2           
 [31] readxl_1.3.1                igraph_1.2.4.1              DBI_1.0.0                  
 [34] htmlwidgets_1.5.1           stats4_3.6.1                riverplot_0.6              
 [37] RSpectra_0.15-0             crosstalk_1.0.0             backports_1.1.5            
 [40] annotate_1.62.0             gbRd_0.4-11                 gridBase_0.4-7             
 [43] locfdr_1.1-8                RcppParallel_4.4.4          vctrs_0.2.0                
 [46] SingleCellExperiment_1.6.0  remotes_2.1.0               ROCR_1.0-7                 
 [49] withr_2.1.2                 batchelor_1.0.1             prettyunits_1.0.2          
 [52] mclust_5.4.5                softImpute_1.4              cluster_2.1.0              
 [55] gsl_2.1-6                   ape_5.3                     ADGofTest_0.3              
 [58] lazyeval_0.2.2              crayon_1.3.4                genefilter_1.66.0          
 [61] glmnet_2.0-18               edgeR_3.26.8                pkgconfig_2.0.3            
 [64] labeling_0.3                GenomeInfoDb_1.20.0         vipor_0.4.5                
 [67] nlme_3.1-141                rlang_0.4.2                 globals_0.12.4             
 [70] lifecycle_0.1.0             miniUI_0.1.1.1              registry_0.5-1             
 [73] doSNOW_1.0.18               modelr_0.1.5                rsvd_1.0.2                 
 [76] cellranger_1.1.0            matrixStats_0.55.0          lmtest_0.9-37              
 [79] rngtools_1.4                Rhdf5lib_1.6.3              zoo_1.8-6                  
 [82] beeswarm_0.2.3              ggridges_0.5.1              png_0.1-7                  
 [85] viridisLite_0.3.0           stabledist_0.7-1            bitops_1.0-6               
 [88] R.oo_1.23.0                 rncl_0.8.3                  KernSmooth_2.23-15         
 [91] blob_1.2.0                  DelayedMatrixStats_1.6.1    rgl_0.100.30               
 [94] manipulateWidget_0.10.0     zinbwave_1.6.0              S4Vectors_0.22.1           
 [97] scales_1.1.0                memoise_1.1.0               magrittr_1.5               
[100] plyr_1.8.4                  ica_1.0-2                   howmany_0.3-1              
[103] gplots_3.0.1.1              bibtex_0.4.2                gdata_2.18.0               
[106] zlibbioc_1.30.0             compiler_3.6.1              lsei_1.2-0                 
[109] fitdistrplus_1.0-14         cli_1.1.0                   ade4_1.7-13                
[112] XVector_0.24.0              listenv_0.7.0               pbapply_1.4-2              
[115] MASS_7.3-51.4               tidyselect_0.2.5            stringi_1.4.3              
[118] copula_0.999-19.1           BiocSingular_1.0.0          locfit_1.5-9.1             
[121] ggrepel_0.8.1               grid_3.6.1                  tools_3.6.1                
[124] future.apply_1.3.0          rstudioapi_0.10             uuid_0.1-2                 
[127] foreach_1.4.7               RNeXML_2.3.0                gridExtra_2.3              
[130] farver_2.0.1                Rtsne_0.15                  digest_0.6.23              
[133] BiocManager_1.30.9          FNN_1.1.3                   shiny_1.4.0                
[136] GenomicRanges_1.36.1        broom_0.5.2                 SDMTools_1.1-221.1         
[139] later_1.0.0                 RcppAnnoy_0.0.13            httr_1.4.1                 
[142] AnnotationDbi_1.46.1        npsurv_0.4-0                kernlab_0.9-27             
[145] Rdpack_0.11-0               colorspace_1.4-1            rvest_0.3.4                
[148] XML_3.98-1.20               reticulate_1.13             clusterExperiment_2.4.4    
[151] IRanges_2.18.3              splines_3.6.1               uwot_0.1.4                 
[154] scater_1.12.2               plotly_4.9.0                xtable_1.8-4               
[157] jsonlite_1.6                zeallot_0.1.0               R6_2.4.1                   
[160] pillar_1.4.2                htmltools_0.4.0             mime_0.7                   
[163] NMF_0.21.0                  glue_1.3.1                  fastmap_1.0.1              
[166] pspline_1.0-18              BiocParallel_1.18.1         BiocNeighbors_1.2.0        
[169] codetools_0.2-16            tsne_0.1-3                  pcaPP_1.9-73               
[172] mvtnorm_1.0-11              lattice_0.20-38             numDeriv_2016.8-1.1        
[175] ggbeeswarm_0.6.0            leiden_0.3.1                gtools_3.8.1               
[178] survival_2.44-1.1           limma_3.40.6                munsell_0.5.0              
[181] rhdf5_2.28.1                GenomeInfoDbData_1.2.1      iterators_1.0.12           
[184] HDF5Array_1.12.3            haven_2.1.1                 reshape2_1.4.3             
[187] gtable_0.3.0

**Comment by jw156605** [comment] 2020-06-02 01:34
Closing old issue.

**Closed by jw156605** 2020-06-02 01:34 UTC

**Comment by fbrundu** [comment] 2020-11-24 14:47
Hi, I'm still facing this issue on LIGER's latest version (0.5.0). I tested both num.cores = 1 and num.cores = 4 but suggestLambda still fails on a particular dataset (but not on a similar dataset). I cannot provide a small dataset to reproduce it but I can test it on my machine if possible. Thanks

**Comment by schroeme** [comment] 2021-03-26 21:57
I am having the same issue. sessionInfo() below.

R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /home/mschro/anaconda3/envs/liger_clone/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SeuratWrappers_0.2.0 reticulate_1.16      loomR_0.2.1.9000    
 [4] hdf5r_1.3.3          R6_2.4.0             Seurat_3.2.0        
 [7] liger_0.5.0          patchwork_1.0.1      Matrix_1.2-17       
[10] cowplot_1.0.0       

loaded via a namespace (and not attached):
  [1] nlme_3.1-139          bit64_4.0.2           RcppAnnoy_0.0.16     
  [4] RColorBrewer_1.1-2    httr_1.4.0            repr_0.19.2          
  [7] sctransform_0.2.1     tools_3.6.1           irlba_2.3.3          
 [10] rpart_4.1-15          KernSmooth_2.23-15    uwot_0.1.8           
 [13] mgcv_1.8-28           lazyeval_0.2.2        colorspace_1.4-1     
 [16] tidyselect_0.2.5      gridExtra_2.3         bit_4.0.4            
 [19] compiler_3.6.1        plotly_4.9.2.1        scales_1.0.0         
 [22] lmtest_0.9-37         spatstat.data_1.4-3   ggridges_0.5.2       
 [25] pbapply_1.4-3         rappdirs_0.3.1        goftest_1.2-2        
 [28] spatstat_1.64-1       pbdZMQ_0.3-3          stringr_1.4.0        
 [31] digest_0.6.18         spatstat.utils_1.17-0 base64enc_0.1-3      
 [34] pkgconfig_2.0.2       htmltools_0.3.6       htmlwidgets_1.3      
 [37] rlang_0.3.4           FNN_1.1.3             shiny_1.3.2          
 [40] zoo_1.8-6             riverplot_0.6         jsonlite_1.6         
 [43] ica_1.0-2             mclust_5.4.6          dplyr_0.8.0.1        
 [46] magrittr_1.5          Rcpp_1.0.1            IRkernel_0.8.15      
 [49] munsell_0.5.0         abind_1.4-5           ape_5.4-1            
 [52] stringi_1.4.3         MASS_7.3-51.3         Rtsne_0.15           
 [55] plyr_1.8.4            grid_3.6.1            parallel_3.6.1       
 [58] listenv_0.8.0         promises_1.0.1        ggrepel_0.8.2        
 [61] crayon_1.3.4          doSNOW_1.0.18         deldir_0.1-28        
 [64] miniUI_0.1.1.1        lattice_0.20-38       IRdisplay_0.7.0      
 [67] splines_3.6.1         tensor_1.5            pillar_1.3.1         
 [70] igraph_1.2.5          uuid_0.1-2            future.apply_1.6.0   
 [73] reshape2_1.4.3        codetools_0.2-16      leiden_0.3.3         
 [76] glue_1.3.1            evaluate_0.13         remotes_2.2.0        
 [79] BiocManager_1.30.10   data.table_1.12.2     png_0.1-7            
 [82] httpuv_1.5.1          foreach_1.4.4         gtable_0.3.0         
 [85] RANN_2.6.1            purrr_0.3.2           polyclip_1.10-0      
 [88] tidyr_0.8.3           future_1.18.0         assertthat_0.2.1     
 [91] ggplot2_3.1.1         rsvd_1.0.3            mime_0.6             
 [94] xtable_1.8-4          later_0.8.0           survival_2.44-1.1    
 [97] viridisLite_0.3.0     tibble_2.1.1          snow_0.4-3           
[100] iterators_1.0.10      cluster_2.0.8         globals_0.12.5       
[103] fitdistrplus_1.1-1    ROCR_1.0-11

**Comment by cgao90** [comment] 2021-03-27 22:11
Hello @fbrundu @schroeme , 

Could you try installing the latest LIGER (V1.0.0) from github and run `suggestLambda` again? Please load the package using `library(rliger)` since is has been renamed recently.

Thanks!

**Comment by schroeme** [comment] 2021-03-28 12:15
Hi @cgao90, this issue persists with LIGER 1.0.0. sessionInfo and error message are pasted below. 
----------------------------------------------------------------------------------------------------
Finished in 7.417137 mins, 48 iterations.
Max iterations set: 100.
Final objective delta: 9.72379e-05.
Best results with seed 1.
Testing different choices of lambda values
Error in {: task 3 failed - "missing value where TRUE/FALSE needed"
Traceback:

1. suggestLambda(liger_small, k = 30, num.cores = 10)
2. foreach(i = 1:length(lambda.test), .combine = "rbind", .packages = "rliger") %dopar% 
 .     {
 .         if (i != 1) {
 .             if (gen.new) {
 .                 ob.test <- optimizeALS(object, k = k, lambda = lambda.test[i], 
 .                   thresh = thresh, max.iters = max.iters, rand.seed = (rand.seed + 
 .                     r - 1))
 .             }
 .             else {
 .                 ob.test <- optimizeNewLambda(object, new.lambda = lambda.test[i], 
 .                   thresh = thresh, max.iters = max.iters, rand.seed = (rand.seed + 
 .                     r - 1))
 .             }
 .         }
 .         else {
 .             ob.test <- object
 .         }
 .         ob.test <- quantileAlignSNF(ob.test, knn_k = knn_k, k2 = k2, 
 .             resolution = resolution, ref_dataset = ref_dataset, 
 .             id.number = i)
 .         calcAlignment(ob.test)
 .     }
3. e$fun(obj, substitute(ex), parent.frame(), e$data)
-----------------------------------------------------------------------------------
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /home/mschro/anaconda3/envs/liger_clone/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SeuratWrappers_0.2.0 reticulate_1.16      loomR_0.2.1.9000    
 [4] hdf5r_1.3.3          R6_2.5.0             Seurat_3.2.0        
 [7] rliger_1.0.0         patchwork_1.1.1      Matrix_1.3-2        
[10] cowplot_1.1.1       

loaded via a namespace (and not attached):
  [1] nlme_3.1-152          bit64_4.0.5           RcppAnnoy_0.0.18     
  [4] doParallel_1.0.16     RColorBrewer_1.1-2    httr_1.4.2           
  [7] repr_0.19.2           sctransform_0.2.1     tools_3.6.1          
 [10] utf8_1.2.1            irlba_2.3.3           rpart_4.1-15         
 [13] KernSmooth_2.23-15    uwot_0.1.10           mgcv_1.8-34          
 [16] DBI_1.0.0             lazyeval_0.2.2        colorspace_2.0-0     
 [19] gridExtra_2.3         tidyselect_1.1.0      bit_4.0.4            
 [22] compiler_3.6.1        plotly_4.9.2.1        scales_1.1.1         
 [25] spatstat.data_1.4-3   lmtest_0.9-37         ggridges_0.5.2       
 [28] pbapply_1.4-3         rappdirs_0.3.1        goftest_1.2-2        
 [31] spatstat_1.64-1       stringr_1.4.0         pbdZMQ_0.3-3         
 [34] digest_0.6.27         spatstat.utils_1.17-0 base64enc_0.1-3      
 [37] pkgconfig_2.0.3       htmltools_0.3.6       htmlwidgets_1.3      
 [40] rlang_0.4.10          FNN_1.1.3             shiny_1.3.2          
 [43] generics_0.1.0        zoo_1.8-6             riverplot_0.10       
 [46] jsonlite_1.7.2        ica_1.0-2             mclust_5.4.7         
 [49] dplyr_1.0.5           magrittr_2.0.1        Rcpp_1.0.6           
 [52] IRkernel_0.8.15       munsell_0.5.0         fansi_0.4.2          
 [55] abind_1.4-5           ape_5.4-1             lifecycle_1.0.0      
 [58] stringi_1.4.3         MASS_7.3-53.1         Rtsne_0.15           
 [61] plyr_1.8.6            grid_3.6.1            parallel_3.6.1       
 [64] listenv_0.8.0         promises_1.0.1        ggrepel_0.9.1        
 [67] crayon_1.4.1          deldir_0.1-28         miniUI_0.1.1.1       
 [70] lattice_0.20-41       IRdisplay_0.7.0       splines_3.6.1        
 [73] tensor_1.5            pillar_1.5.1          igraph_1.2.5         
 [76] uuid_0.1-2            reshape2_1.4.3        future.apply_1.6.0   
 [79] codetools_0.2-16      leiden_0.3.3          glue_1.4.2           
 [82] evaluate_0.13         remotes_2.2.0         BiocManager_1.30.10  
 [85] data.table_1.12.2     vctrs_0.3.6           png_0.1-7            
 [88] httpuv_1.5.1          foreach_1.5.1         polyclip_1.10-0      
 [91] gtable_0.3.0          RANN_2.6.1            purrr_0.3.4          
 [94] tidyr_0.8.3           future_1.18.0         ggplot2_3.3.3        
 [97] rsvd_1.0.3            mime_0.6              xtable_1.8-4         
[100] later_0.8.0           survival_2.44-1.1     viridisLite_0.3.0    
[103] tibble_3.1.0          iterators_1.0.13      cluster_2.0.8        
[106] globals_0.12.5        fitdistrplus_1.1-1    ellipsis_0.3.1       
[109] ROCR_1.0-11

**Comment by cgao90** [comment] 2021-04-02 16:58
Hi @schroeme ,

Sorry we have not been able to reproduce the error. In practice, lambda = 5 works well for most of the analyses. Have you tried this setting for yours?

**Comment by schroeme** [comment] 2021-04-25 23:22
Hi @cgao90, Yes, I have tried this. Empirically I am finding very different integrations with different lambda values at and around 5, so it would be useful to see the curve to know where the alignment score plateaus.

**Comment by cgao90** [comment] 2021-05-04 15:16
Hi @schroeme , this curve can be achieved in this way: For a range of lambda values, 1) run the analysis; 2) call `calcAlignment` to get the corresponding score. In the end, make lambda vs alignment score plot and identify the "elbow". Hope it would address your need. Sorry about the inconvenience.
